name: SMS Reminders
on:
  schedule:
    - cron: "0 12 * * *" # tous les jours à midi
jobs:
  sms:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          curl -X POST ${{ secrets.APP_BASE_URL }}/api/sms/send \
            -H "Content-Type: application/json" \
            -d '{"to":"${{ secrets.TEST_SMS_TO }}","message":"Rappel : vous avez un rendez-vous aujourd’hui."}'
